#!/bin/bash

fancy_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  zshrc="$HOME/.zshrc"

  if ! grep -Fqs "$text" "$zshrc"; then
      printf "\n%s\n" "$text" >> "$zshrc"
  fi
}

setup_host() {
  if [ ! -f "$HOME/.host" ]; then
    host=''
    while [[ $host == '' ]]
    do
      read -p "Set your hostname to something sensible ie (peterslaptop): " host
    done
    echo "Goign to setup hostname to: $host"
    sudo scutil --set HostName $host
    sudo sh -c "echo '127.0.0.1 $host\n::1 $host' >> /etc/hosts"
    echo $host > ~/.host
  fi
}

setup_ruby() {
  brew_install_or_upgrade 'gpg'
  gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  curl -sSL https://get.rvm.io | bash
  source $HOME/.rvm/scripts/rvm
  rvm reload
  rvm install 2.7.1
}

setup_node() {
  brew_install_or_upgrade 'nvm'
  mkdir -p ~/.nvm
  append_to_zshrc 'export NVM_DIR="$HOME/.nvm"'
  append_to_zshrc '[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"'
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
  nvm install 10.15.1
  npm install -g npm@6.4.1
}

setup_java() {
  curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
  [ -s "$JABBA_HOME/jabba.sh" ] && source "$JABBA_HOME/jabba.sh"
  jabba install adopt@1.11.0-4
  jabba install adopt@1.8.0-232
  jabba alias default adopt@1.11.0-4
  jabba use default
}

setup_zsh() {
  if [ -d "$HOME/.oh-my-zsh" ]; then
    echo "zsh already installed"
  else
    curl -L http://install.ohmyz.sh | sh
  fi

  if [ ! -d "$HOME/.bin/" ]; then
    mkdir "$HOME/.bin"
  fi

  if [ ! -f "$HOME/.zshrc" ]; then
    touch "$HOME/.zshrc"
  fi

  append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

  case "$SHELL" in
    */zsh) : ;;
    *)
      fancy_echo "Changing your shell to zsh ..."
        chsh -s "$(which zsh)"
      ;;
  esac
}

brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      fancy_echo "Upgrading %s ..." "$1"
      brew upgrade "$@"
    else
      fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
    fi
  else
    fancy_echo "Installing %s ..." "$1"
    brew install "$@"
  fi
}

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"

  ! brew outdated --quiet "$name" >/dev/null
}

brew_tap() {
  echo "brew tap $1"
  brew tap "$1"
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_services_start() {
  local name="$(brew_expand_alias "$1")"
  fancy_echo "Restarting %s ..." "$1"
  brew services start $name
}

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  else
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
    rbenv rehash
  fi
}


setup_ssh() {
  if [ -w "$HOME/.ssh/id_rsa" ]; then
    echo "ssh key already exists"
  else
    ssh-keygen
  fi
}

setup_homebrew() {
  if ! command -v brew >/dev/null; then
    fancy_echo "Installing Homebrew ..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      append_to_zshrc '# recommended by brew doctor'

      # shellcheck disable=SC2016
      append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

      export PATH="/usr/local/bin:$PATH"
  else
    fancy_echo "Homebrew already installed. Skipping ..."
  fi

  fancy_echo "Updating Homebrew formulas ..."
  brew update
}

setup_xcode() {
  echo "installing xcode tools"
  xcode-select --install || true
  xcode-select -v
}

setup_software() {
  brew_tap 'mongodb/brew'

  brew_install_or_upgrade 'cask'
  brew_install_or_upgrade 'git'
  brew_install_or_upgrade 'redis'
  brew_services_start 'redis'
  brew_install_or_upgrade 'vim'
  brew_install_or_upgrade 'openssl'
  brew_install_or_upgrade 'tree'
  brew_install_or_upgrade 'git-flow'
  brew_install_or_upgrade 'gnuplot'
  brew_install_or_upgrade 'libpng'
  brew_install_or_upgrade 'wget'
  brew_install_or_upgrade 'cmake'
  brew_install_or_upgrade 'lynx'
  brew_install_or_upgrade 'readline'
  brew_install_or_upgrade 'gettext'
  brew_install_or_upgrade 'sqlite'
  brew_install_or_upgrade 'htop-osx'
  brew_install_or_upgrade 'emacs'
  brew_install_or_upgrade 'r'
  brew_install_or_upgrade 's3cmd'
  brew_install_or_upgrade 'pinentry-mac'
  brew_install_or_upgrade 'python'

  brew cask install xquartz
  brew cask install google-chrome
  brew cask install zoom
  brew cask install firefox
  brew cask install google-hangouts
  brew cask install disk-inventory-x
  brew cask install iterm2
  brew cask install slack
  brew cask install authy
  brew cask install atom
  brew cask install chromedriver
  brew cask install ngrok
  brew cask install intellij-idea
  brew cask install discord
}

setup_env() {
  append_to_zshrc 'plugins=(aws common-aliases git git-flow mvn npm pod osxscreen gradle)'
  append_to_zshrc 'export LC_CTYPE=en_US.UTF-8'
  append_to_zshrc 'export LANGUAGE=en_US.UTF-8'
  append_to_zshrc 'export LANG=en_US.UTF-8'
  append_to_zshrc 'export LC_ALL=en_US.UTF-8'
  append_to_zshrc 'export EDITOR=vim'
  append_to_zshrc 'export VISUAL=vim'
  append_to_zshrc 'setopt SHARE_HISTORY'
  append_to_zshrc 'setopt EXTENDED_HISTORY'
  append_to_zshrc 'export PATH=/usr/local/bin:$PATH'
  append_to_zshrc 'export GPG_TTY=$(tty)'

}

#beginning of runnign code
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e
setup_host
setup_ssh
setup_xcode
setup_homebrew
setup_zsh
setup_java
setup_ruby
setup_node
setup_software
setup_env
